name: Deploy do Homolog Main

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run deploy:homolog

  job-tag:
    name: job-tag
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
          echo "BRANCH MAIN Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "BRANCH MAIN Tag name from github.ref_name: ${{  github.ref_name }}"
          tag=$(git describe --tags --abbrev=0)
          echo "$tag":refs/tags/"$tag"
